config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :bicycles

  root 'bicycles#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/bicycle.rb
class Bicycle < ActiveRecord::Base
  validates_presence_of :name, :style, :price
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bicycles_controller.rb
class BicyclesController < ApplicationController
  before_action :set_bicycle, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:new, :edit, :create, :update, :destroy]

  # GET /bicycles
  # GET /bicycles.json
  def index
    @bicycles = Bicycle.all
  end

  # GET /bicycles/1
  # GET /bicycles/1.json
  def show
  end

  # GET /bicycles/new
  def new
    @bicycle = Bicycle.new
  end

  # GET /bicycles/1/edit
  def edit
  end

  # POST /bicycles
  # POST /bicycles.json
  def create
    @bicycle = Bicycle.new(bicycle_params)

    respond_to do |format|
      if @bicycle.save
        format.html { redirect_to @bicycle, notice: 'Bicycle was successfully created.' }
        format.json { render :show, status: :created, location: @bicycle }
      else
        format.html { render :new }
        format.json { render json: @bicycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bicycles/1
  # PATCH/PUT /bicycles/1.json
  def update
    respond_to do |format|
      if @bicycle.update(bicycle_params)
        format.html { redirect_to @bicycle, notice: 'Bicycle was successfully updated.' }
        format.json { render :show, status: :ok, location: @bicycle }
      else
        format.html { render :edit }
        format.json { render json: @bicycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bicycles/1
  # DELETE /bicycles/1.json
  def destroy
    @bicycle.destroy
    respond_to do |format|
      format.html { redirect_to bicycles_url, notice: 'Bicycle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bicycle
      @bicycle = Bicycle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bicycle_params
      params.require(:bicycle).permit(:name, :photo, :style, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bicycles_helper.rb
module BicyclesHelper
end

app/views/bicycles/_form.html.haml
= form_for @bicycle, html: { class: "form form-horizontal bicycle" } do |f|
  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    = error_span(@bicycle[:name])
  .form-group
    = f.label :photo, class: 'control-label'
    .controls
      = f.text_field :photo, class: 'form-control', required: true
    = error_span(@bicycle[:photo])
  .form-group
    = f.label :style, class: 'control-label'
    .controls
      = f.text_field :style, class: 'form-control', required: true
    = error_span(@bicycle[:style])
  .form-group
    = f.label :price, class: 'control-label'
    .controls
      = f.text_field :price, class: 'form-control', required: true
    = error_span(@bicycle[:price])
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), bicycles_path, :class => 'btn btn-default'

app/views/bicycles/edit.html.haml
- model_class = Bicycle
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/bicycles/index.html.haml
- @bicycles.each do |bicycle|
  .col-lg-3.col-md-4.bicycle-item
    -if current_admin
      .actions
        = link_to t('.edit', :default => t("helpers.links.edit")), edit_bicycle_path(bicycle), :class => 'btn btn-default btn-xs'
        = link_to t('.destroy', :default => t("helpers.links.destroy")), bicycle_path(bicycle), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'delete btn btn-xs btn-danger'
    =link_to bicycle do
      .img
        =image_tag bicycle.photo
      .desc
        .name.h5
          =bicycle.name
        .style.h6
          =bicycle.style
      .price
        ="$#{bicycle.price}"



         

app/views/bicycles/new.html.haml
- model_class = Bicycle
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/bicycles/show.html.haml
%center
  %p
    =image_tag @bicycle.photo
  %p
    %strong
      = "Name :"
    = @bicycle.name
  %p
    %strong
      = "Style : "
    = @bicycle.style
  %p
    %strong
      ="Price :"
    = @bicycle.price

  
  = link_to t('.back', :default => t("helpers.links.back")), bicycles_path, :class => 'btn btn-default'
  -if current_admin
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_bicycle_path(@bicycle), :class => 'btn btn-default'
    = link_to t('.destroy', :default => t("helpers.links.destroy")), bicycle_path(@bicycle), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'delete btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "BicyclePortal"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="/") BicyclePortal
        -if current_admin
          .navbar-collapse.collapse.navbar-responsive-collapse
            %ul.nav.navbar-nav
              %li= link_to "Create New Bicycle", "#{new_bicycle_path}"
              %li= link_to "logout", "#{destroy_admin_session_path}", :method => :delete




    .container
      .row
        = bootstrap_flash
        = yield
      / %footer
      /   %p &copy; Company 2015